###
GET http://localhost:1234/notes

###

POST http://localhost:1234/notes
Content-Type: application/json

{
    "sql": "oaaoeuaoeu",
    "title": "Segunda Nota",
    "description": "Contenido de la segunda Nota"
}

###

DELETE http://localhost:1234/notes/2

###

PATCH http://localhost:1234/notes/1
Content-Type: application/json

{
    "sql": "oaaoeuaoeu",
    "title": "other Title"
}